function resized(){
	var ww=$(window).width();
	var wh=$(window).height();
	$('#content').height(wh-100);
	$('.box').css('left',((ww-880)/2)+'px').css('top',((wh-800)/2)+'px');
	$('.close').css('left',((ww-80)/2)+'px');
	$('#ie_bad_bg').width(ww).height(wh);
	$('#ie_bad').css('top',(wh-300)/2+'px').css('left',(ww-400)/2+'px');
}
resized();
$(window).resize(function(){
	resized();
});
$('.img1').click(function(){
	$('#z2').css('display','block');
	$('.box').css('display','none');
	$('.box1').css('display','block');
});
$('.img2').click(function(){
	$('#z2').css('display','block');
	$('.box').css('display','none');
	$('.box2').css('display','block');
});
$('.img3').click(function(){
	$('#z2').css('display','block');
	$('.box').css('display','none');
	$('.box3').css('display','block');
});
$('.img4').click(function(){
	$('#z2').css('display','block');
	$('.box').css('display','none');
	$('.box4').css('display','block');
});
$('.img5').click(function(){
	$('#z2').css('display','block');
	$('.box').css('display','none');
	$('.box5').css('display','block');
});
$('.img6').click(function(){
	$('#z2').css('display','block');
	$('.box').css('display','none');
	$('.box6').css('display','block');
});
$('.close').click(function(){
	$('#z2').css('display','none');
	$('.box').css('display','none');
});